services:
  - type: web
    name: yelpcamp
    env: node
    runtime: node
    buildCommand: npm install
    startCommand: node ./app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: MAPTILER_API_KEY
        sync: false